### ISSUE TITLE
Grails 4: Field guide download returns empty PDF on test

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/specieslist-webapp#201]
View a list on test site: https://lists-test.ala.org.au/speciesListItem/list/dr12238

click download button at top, then select the "download species field guide" option. Resulting PDF has no species listed. Same list on prod shows profiles for species.

**Comment by Rita-C** [comment]
on test:
```
mysql> select specieslis0_.guid as col_0_0_ from species_list_item specieslis0_ where specieslis0_.data_resource_uid='dr12238' and (specieslis0_.guid is not null) 
    -> ;                                      |
+-------------------------------------------------+
| http://id.biodiversity.org.au/node/apni/2886562 |
| http://id.biodiversity.org.au/node/apni/2904374 |
| http://id.biodiversity.org.au/node/apni/2892890 |
| http://id.biodiversity.org.au/node/apni/2902910 |
| http://id.biodiversity.org.au/node/apni/2917026 |
| http://id.biodiversity.org.au/node/apni/2911902 |
| http://id.biodiversity.org.au/node/apni/2907350 |
| http://id.biodiversity.org.au/node/apni/2902237 |
| http://id.biodiversity.org.au/node/apni/2898831 |
| http://id.biodiversity.org.au/node/apni/2903282 |
| http://id.biodiversity.org.au/node/apni/2891254 |
| http://id.biodiversity.org.au/node/apni/2904629 |
| http://id.biodiversity.org.au/node/apni/2896783 |
| http://id.biodiversity.org.au/node/apni/2893725 |
| http://id.biodiversity.org.au/node/apni/2898882 |
| http://id.biodiversity.org.au/node/apni/2911196 |
| http://id.biodiversity.org.au/node/apni/2915163 |
| http://id.biodiversity.org.au/node/apni/2906316 |
| http://id.biodiversity.org.au/node/apni/2914687 |
| http://id.biodiversity.org.au/node/apni/2902310 |
| http://id.biodiversity.org.au/node/apni/2914220 |
| http://id.biodiversity.org.au/node/apni/2901189 |
| http://id.biodiversity.org.au/node/apni/2911745 |
| http://id.biodiversity.org.au/node/apni/2891544 |
+-------------------------------------------------+
24 rows in set (0.00 sec)
```

on prod:
```
+----------------------------------------------------+
| https://id.biodiversity.org.au/taxon/apni/51286005 |
| https://id.biodiversity.org.au/node/apni/2904374   |
| https://id.biodiversity.org.au/node/apni/2892890   |
| https://id.biodiversity.org.au/node/apni/2902910   |
| https://id.biodiversity.org.au/node/apni/2917026   |
| https://id.biodiversity.org.au/node/apni/2911902   |
| https://id.biodiversity.org.au/node/apni/2907350   |
| https://id.biodiversity.org.au/node/apni/2902237   |
| https://id.biodiversity.org.au/node/apni/2898831   |
| https://id.biodiversity.org.au/node/apni/2903282   |
| https://id.biodiversity.org.au/node/apni/2891254   |
| https://id.biodiversity.org.au/node/apni/2904629   |
| https://id.biodiversity.org.au/node/apni/2896783   |
| https://id.biodiversity.org.au/node/apni/2893725   |
| https://id.biodiversity.org.au/node/apni/2898882   |
| https://id.biodiversity.org.au/node/apni/2911196   |
| https://id.biodiversity.org.au/node/apni/2915163   |
| https://id.biodiversity.org.au/node/apni/2906316   |
| https://id.biodiversity.org.au/node/apni/2914687   |
| https://id.biodiversity.org.au/node/apni/2902310   |
| https://id.biodiversity.org.au/node/apni/2914220   |
| https://id.biodiversity.org.au/node/apni/2901189   |
| https://id.biodiversity.org.au/node/apni/2911745   |
| https://id.biodiversity.org.au/node/apni/2891544   |
+----------------------------------------------------+
24 rows in set (0.00 sec)
```

**Comment by Rita-C** [comment]
mysql on test: 
```
+----------------------------+
| DEFAULT_CHARACTER_SET_NAME |
+----------------------------+
| utf8                       |
```

mysql on prod:
```
+----------------------------+
| default_character_set_name |
+----------------------------+
| latin1      
```

**Comment by Rita-C** [comment]
error on fieldguide (calling `https://fieldguide.ala.org.au/generate` with `guids` as POST body)
```
2021-12-08 15:06:54,220 ERROR [GrailsExceptionResolver] SAXParseException occurred when processing request: [POST] /generate
An invalid XML character (Unicode: 0x1d) was found in the element content of the document.. Stacktrace follows:
org.xml.sax.SAXParseException; lineNumber: 47; columnNumber: 46; An invalid XML character (Unicode: 0x1d) was found in the element content of the document.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:659)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
        at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:189)
        at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:75)
        at grails.plugin.rendering.document.XhtmlDocumentService.createDocument(XhtmlDocumentService.groovy:52)
        at grails.plugin.rendering.document.XhtmlDocumentService.createDocument(XhtmlDocumentService.groovy:40)
        at grails.plugin.rendering.document.XhtmlDocumentService.createDocument(XhtmlDocumentService.groovy:35)
        at grails.plugin.rendering.RenderingService.render(RenderingService.groovy:36)
        at au.org.ala.GenerateService.generate(GenerateService.groovy:61)
        at au.org.ala.fieldguide.GenerateController.index(GenerateController.groovy:19)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by nickdos** [comment]
UTF-8 is preferred. Prod DB is so old so probably has just been copied over for last 8-10 years.

**Comment by Rita-C** [comment]
Re-matched the list, field guide pdf was generated after rematch.

**Comment by Rita-C** [comment]
@nickdos, could you re-test this please?

**Comment by nickdos** [comment]
works for me now ✅
